const pics = [

    "Chick",
    "Chicken",
    "Cow",
    "Goat",
    "Horse",
    "Pig",
    "Sheep",
    "Duck",
    "Dog",
    "Cat",
    "Rabbit",
    "Goldfish",
    "Hamster",
    "Turtle",
    "Kitten",
    "Puppy",
    "Bear",
    "Moose",
    "Fox",
    "Raccoon",
    "Squirrel",
    "Owl",
    "Hedgehog",
    "Baby Penguin",
    "Penguin",
    "Arctic Fox",
    "Snowy Owl",
    "Polar Bear",
    "Arctic Hare",
    "Seal",
    "Walrus",
    "Tiger",
    "Panther",
    "Cockatoo",
    "Orangutan",
    "Anaconda",
    "Macaw",
    "Jaguar",
    "Capuchin",
    "Toucan",
    "Parrot",
    "Elf",
    "Witch",
    "Wizard",
    "Fairy",
    "Slime Monster",
    "Jester",
    "Dragon",
    "Unicorn",
    "Queen",
    "King",
    "Snow Globe",
    "Holiday Gift",
    "Hot Chocolate",
    "Gingerbread Man",
    "Gingerbread House",
    "Holiday Wreath",
    "Snowman",
    "Santa Claus",
    "Two of Spades",
    "Eat Me",
    "Drink Me",
    "Alice",
    "Queen of Hearts",
    "Dormouse",
    "White Rabbit",
    "Cheshire Cat",
    "Caterpillar",
    "Mad Hatter",
    "King of Hearts",
    "Toast",
    "Cereal",
    "Yogurt",
    "Breakfast Combo",
    "Orange Juice",
    "Milk",
    "Waffle",
    "Pancakes",
    "French Toast",
    "Pizza",
    "Sandwich",
    "Light Blue",
    "Black",
    "Red",
    "Purple",
    "Pink",
    "Orange",
    "Lime",
    "Green",
    "Teal",
    "Tan",
    "Maroon",
    "Gray",
    "Mint",
    "Salmon",
    "Burgandy",
    "Baby Blue",
    "Dust",
    "Brown",
    "Dull Blue",
    "Yellow",
    "Blue",
    "Pumpkin",
    "Swamp Monster",
    "Frankenstein",
    "Vampire",
    "Zombie",
    "Mummy",
    "Werewolf",
    "Ghost",
    "Spooky Pumpkin",
    "Spooky Mummy",
    "Spooky Ghost",
    "Toast",
    "Cereal",
    "Yogurt",
    "Orange Juice",
    "Milk",
    "Waffle",
    "Pancakes",
    "French Toast"
];